name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # 4️⃣ Build EXE with PyInstaller
      - name: Build EXE
        run: |
          pyinstaller --onefile main.py
          dir dist

      # 5️⃣ Upload the EXE as an artifact
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: my-windows-exe
          path: dist/main.exe
